version: '3'
services:
  influxdb:
    image: "influxdb:latest"
    environment:
     INFLUXDB_DB: "training"
    ports:
     - "8086:8086"
    volumes:
     - ./influxdb_data:/var/lib/influxdb
  chronograf:
    image: "chronograf:latest"
    command: --influxdb-url=http://influxdb:8086
    ports:
     - "8899:8888"
    volumes:
     - ./chronograf_data:/var/lib/chronograf
    depends_on:
     - influxdb
